version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: jrmonteiro
      ME_CONFIG_BASICAUTH_PASSWORD: teste123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: jrmonteiro
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste123
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: jrmonteiro
      MONGO_INITDB_ROOT_PASSWORD: teste123
    ports:
      - "27017:27017"
    #volumes:
    #  - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
